name = "wc2026guess"
compatibility_date = "2026-06-12"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "wc2026guess"
database_id = "4a437792-f2ca-4877-95c0-0515bd76b5c3"
migrations_dir = "migrations"
